### ISSUE TITLE
Unable to edit a question

### ISSUE THREAD

**Issue by ChillinRage** [CS3219-AY2425S1/cs3219-ay2425s1-project-g34#12]
## Problem
Unable to edit a question's field (description etc.) except for the title.
Picture shown below (editing the description)

![image](https://github.com/user-attachments/assets/49bf4dfa-cfaa-485b-b4b2-0b899f7c182a)
![image](https://github.com/user-attachments/assets/640eeb45-c93d-46ae-a4ae-de8fd4eab7f2)

Expected behavior: successfully updating the `Hihi` question with the new description.
Actual behavior: 
![image](https://github.com/user-attachments/assets/a841662f-fc75-435f-8583-a78324836e8b)

## Error
There is an inconsistency with how the backend checks for changes and how the frontend formats the requests. The requests contains the full details of a question (including the unedited details), but the backend assumes that any field provided in the request are new values to be updated. This causes the backend to think that the "new" title is conflicting with an existing question, throwing the 409 error. 

## Proposed fix
**Quick fix:** under `question-controller.js` line 174, replace the condition with `existingQuestion && existingQuestion.id !== id`.

But in the long term, this inconsistency between the front and back ends might cause other problems. Either the front-end changes how it formats the field, or the back-end changes how it handles request fields.

**Comment by inezkok** [comment]
I fixed it by changing `question-controller.js` line 172 to `title && title !== question.title` not too sure if this causes any inconsistency between the frontend and backend...
